Make the build faster - slimmer drops source
WFCD/warframe-items pull request #156
Opened 2020-09-13 17:48 UTC by TobiTenno

### What did you fix? (provide a description or issue closes statement)
Made the build go faster!
Use all.slim.json instead of all.json from https://drops.warframestat.us

This makes parsing through the items trivial as overhead as opposed to needing to traverse all categories

---

### Reproduction steps
1. Start the build
1. it goes faster

---

### Evidence/screenshot/link to line

You can see my fix [on this line](#line-number-1235234) for where the new data exists

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
- Have I run the linter through `npm run lint`? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**

2020-09-14 10:29 UTC, Kaptard requested changes
There's an issue with the output data of prime Warframes where drop locations are either missing or (probably) incorrect.

Taking Ember Prime as example, the old data had these results:
```
Blueprint: [12]
Chassis: [8]
Neuroptics: [8]
Systems: [8]
Orokin Cell: [95]
```

The new one has these:
```
Blueprint: [24]
Chassis: [0]
Neuroptics: [0]
Systems: [0]
Orokin Cell: [95]
```

[I made a small script to find all the mismatching items here](https://gist.github.com/Kaptard/ba8bf53d3da3889c7ccb0417e4f0cdb8).

Looking at the code I couldn't see any obvious issues. I'll probably get around looking into it more deeply tomorrow if you need debugging help.

2020-09-14 12:50 UTC, TobiTenno commented
Sounds good. Probably need to tweak the name formatting for some prime items, possibly?

2020-09-15 12:55 UTC, Kaptard approved these changes

2020-09-15 12:56 UTC, Kaptard commented
Seems good. There's still some mismatches, but that's because of faulty old data from the few examples I looked at.

2020-09-15 12:58 UTC, merged