Types export
WFCD/warframe-items pull request #459
Opened 2023-08-09 20:16 UTC by BenjaminPalko

### What did you fix? 
![image](https://github.com/WFCD/warframe-items/assets/18660606/7fb458b0-85c1-42cc-9eda-755c20416e19)
Fixed types not being exported properly through package.json as well as set default export to index.js (which covers require and other cases)

---

### Reproduction steps
Install warframe-items as a dependency on a Typescript project (Webstorm)

---

### Evidence/screenshot/link to line

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**

2023-08-09 20:48 UTC, TobiTenno commented
Your description is misleading. This only applies to ESM projects.

2023-08-09 20:48 UTC, TobiTenno requested changes

2023-08-09 20:48 UTC, TobiTenno commented on package.json
> -    "require": "./index.js"
Why? No thanks. Please don't remove an existing.

2023-08-09 21:56 UTC, BenjaminPalko commented
> Your description is misleading. This only applies to ESM projects.

Ty, didn't realize it was only ESM.

2023-08-09 21:58 UTC, TobiTenno approved these changes

2023-08-10 16:42 UTC, TobiTenno commented
uhhhh, looks like some weirdness with types... doubt it's specifically from you, but if you wanna take a look at that error and put a ticket in with the root cause and fix that, can't merge this until that's fixed (sorry)

2023-08-12 00:18 UTC, merged